version: '3'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - .tmp/db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: p4swword!!
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

  db-admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
